allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  cpu-features: true
  prisma: true
  protobufjs: true
  ssh2: true
  unrs-resolver: false
minimumReleaseAgeExclude:
  - nodemailer@10.0.16
